resources:
  - name: goof
    type: git
    icon: github-circle
    source:
      uri: https://github.com/snyk-labs/nodejs-goof

jobs:
  - name: test
    public: true
    plan:
      - get: goof
        trigger: true
      - task: test-using-snyk
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: snyk/snyk-cli, tag: npm }
          params:
            SNYK_TOKEN: ((snyk-token))
          inputs:
            - name: goof
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd goof
                snyk test
