pipeline {
    agent any

    // Install the Jenkins tools you need for your project / environment
    tools {
        snyk 'Snyk' // Refers to a global tool configuration for the Snyk plugin called 'Snyk'
    }

    stages {
        
        stage('Get Repo') {
            steps {
                git url: 'https://github.com/iainrose/terraform-goof'
            }
        }
        
        stage('Run Snyk Scan') {
            steps {
                snykSecurity monitorProjectOnBuild: false, additionalArguments: '--iac, snykInstallation: 'Snyk', snykTokenId: 'snyk_api_token'
            }
        }
    }
}
