pipeline {
    agent any

    // Pull your Snyk token from a Jenkins encrypted credential
    // (type "Secret text"... see https://jenkins.io/doc/book/using/using-credentials/#adding-new-global-credentials)
    // and put it in temporary environment variable for the Snyk CLI to consume.
    environment {
        SNYK_TOKEN = credentials('SNYK_TOKEN')
    }

    stages {

        stage('Initialize & Cleanup Workspace') {
            steps {
               echo 'Initialize & Cleanup Workspace'
               sh 'ls -la'
               sh 'rm -rf *'
               sh 'rm -rf .git'
               sh 'rm -rf .gitignore'
               sh 'ls -la'
            }
        }

        stage('Git Clone') {
            steps {
                git url: 'https://github.com/iainrose/juice-shop.git'
                sh 'ls -la'
            }
        }

        stage('Download Latest Snyk CLI') {
            steps {
                sh '''
                    snyk_cli_dl_mac="https://static.snyk.io/cli/latest/snyk-macos"
                    echo "Download URL: ${snyk_cli_dl_mac}"
                    curl -Lo ./snyk "${snyk_cli_dl_mac}"
                    chmod +x snyk
                    ls -la
                    ./snyk -v
                '''
            }
        }      

        // Run snyk code test to check for vulnerabilities and fail the build if any are found
        // Consider using --severity-threshold=<low|medium|high> for more granularity (see snyk help for more info).
        stage('Snyk Code Test using Snyk CLI') {
            steps {
                sh './snyk code test'
            }
        }

    }
}
