pipeline {
    agent any

    // Install the Jenkins tools you need for your project / environment
    tools {
        nodejs 'Node' // Refers to a global tool configuration for NodeJS called 'node'
    }

    // Pull your Snyk token from a Jenkins encrypted credential
    // (type "Secret text"... see https://jenkins.io/doc/book/using/using-credentials/#adding-new-global-credentials)
    // and put it in temporary environment variable for the Snyk CLI to consume.
    environment {
        SNYK_TOKEN = credentials('SNYK_TOKEN')
    }

    stages {

        stage('Initialize & Cleanup Workspace') {
            steps {
               echo 'Initialize & Cleanup Workspace'
               sh 'ls -la'
               sh 'rm -rf *'
               sh 'rm -rf .git'
               sh 'rm -rf .gitignore'
               sh 'ls -la'
            }
        }

        stage('Git Clone') {
            steps {
                git url: 'https://github.com/iainrose/juice-shop.git'
                sh 'ls -la'
            }
        }

        stage('Test Build Requirements') {
            steps {
                sh 'node --version'
            }
        }

        stage('Install Snyk CLI') {
            steps {
                sh 'npm install -g snyk'
            }
        }  

        stage('Test Snyk CLI') {
            steps {
                sh 'snyk --version'
            }
        }        

        // Run snyk test to check for vulnerabilities and fail the build if any are found
        // Consider using --severity-threshold=<low|medium|high> for more granularity (see snyk help for more info).
        stage('Snyk Test using Snyk CLI') {
            steps {
                sh 'snyk code test --severity-threshold=high'
            }
        }

    }
}
