
pipeline {
    agent any

    stages {

        stage('Download Latest Snyk CLI') {
            steps {
                sh '''
                    snyk_cli_dl_mac="https://static.snyk.io/cli/latest/snyk-macos"
                    echo "Download URL: ${snyk_cli_dl_mac}"
                    curl -Lo ./snyk "${snyk_cli_dl_mac}"
                    chmod +x snyk
                    ls -la
                    ./snyk -v
                '''
            }
        }
    }
}
